### ISSUE TITLE
Set Sender ID

### ISSUE THREAD

**Issue by KidA001** [Fedcomp/any_sms-backend-aws#1]
On your `sns_client` object you can do
```ruby
sns_client.set_sms_attributes({ 'DefaultSenderID' => 'SomeSenderId' })
```

It's built into the AWS-SDK. Hope that helps!

**Comment by Fedcomp** [comment]
Thank you, indeed it helps! i hope i can implement this feature soon, thank you again.

**Comment by Fedcomp** [comment]
added in https://github.com/Fedcomp/any_sms-backend-aws/commit/c81757121640c584e61df57d4604edc7826ae75f
